# 1. CORE SETTINGS
set -g mouse on
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on
set -g default-terminal "tmux-256color"
set -g terminal-overrides ",xterm-256color:RGB"
set -g status-position top

# 2. KEYBINDINGS
bind r source-file ~/.config/tmux/tmux.conf \; display "Reloaded!"
bind c new-window -c "#{pane_current_path}"
bind Space last-window
bind C-b run-shell "tmux setw -g status \$(tmux show -g -w status | grep -q off && echo on || echo off)"
bind w choose-tree -Zrw -O name
bind s choose-tree -Zrs -O name

# Popup for Lazygit
bind g if-shell -F '#{==:#{session_name},popup}' {
    detach-client
} {
    display-popup -d "#{pane_current_path}" -w90% -h90% -E "tmux attach-session -t popup || tmux new-session -s popup lazygit"
}

# TMUX-FZF CONFIG
set -g @plugin 'sainnhe/tmux-fzf'
set-environment -g TMUX_FZF_LAUNCH_KEY ""
set-environment -g TMUX_FZF_OPTIONS "-p -w 80% -h 60%"
set-environment -g TMUX_FZF_WINDOW_FORMAT "#{window_name}"
bind W run-shell -b "~/.config/tmux/scripts/window-switch-with-icons.sh"

# 3. PLUGINS (Define all plugins here)
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'catppuccin/tmux'
set -g @plugin 'jaclu/tmux-menus'
set -g @plugin 'noscript/tmux-mighty-scroll'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-sensible'
# set -g @plugin 'binoymanoj/tmux-minimal-theme'
# set -g @sessionx-preview-enabled 'false'
#
# # 1. Map icons to session names (Nerd Font icons)
# # Format: 'name:icon'
# set -g @sessionx-custom-paths-display-ids 'portal:󰈻,config:,popup:'
#
# # 2. Add some spacing and fzf polish to the output
# # This makes the pointer match your Catppuccin theme
# set -g @sessionx-pointer-color '#f5e0dc'
#
# # 3. Use additional-options to clean up the fzf UI
# # This forces fzf to behave like a clean menu
# set -g @sessionx-additional-options "--prompt='󱂬 ' --pointer='▶' --layout=reverse"
#
# # 4. Search by path logic
# set -g @sessionx-filter-by-path 'on'
#
# 5. RESURRECT & CONTINUUM CONFIG
set -g @resurrect-strategy-nvim 'session'
set -g @continuum-restore 'on'
set -g @continuum-save-interval '1'

# 6. CATPPUCCIN CONFIG
# set -g @catppuccin_flavour 'mocha'
# set -g @catppuccin_window_left_separator ""
# set -g @catppuccin_window_right_separator " "
# set -g @catppuccin_window_middle_separator " █"
# set -g @catppuccin_window_number_position "right"
# set -g @catppuccin_window_default_fill "number"
# set -g @catppuccin_window_current_fill "number"
# set -g @catppuccin_window_current_text "#{pane_current_path}"
#
# set -g @catppuccin_status_modules_right "directory session"
# set -g @catppuccin_status_left_separator  " "
# set -g @catppuccin_status_right_separator ""
# set -g @catppuccin_status_fill "icon"
# set -g @catppuccin_status_connect_separator "no"
# set -g @catppuccin_directory_text "#{pane_current_path}"

# 7. INITIALIZE TPM (Keep this at the very bottom!)
run '~/.config/tmux/plugins/tpm/tpm'
