start-at-login = true

# You can use it to add commands that run after login to macOS user session.
# 'start-at-login' needs to be 'true' for 'after-login-command' to work
after-login-command = []

# You can use it to add commands that run after AeroSpace startup.
# 'after-startup-command' is run after 'after-login-command'
after-startup-command = [
    'exec-and-forget borders active_color=0xffffffff inactive_color=0xff494d64 width=12.0'
]

enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true
automatically-unhide-macos-hidden-apps = true

accordion-padding = 30

default-root-container-layout = 'tiles'

# Possible values: horizontal|vertical|auto
# 'auto' means: wide monitor (anything wider than high) gets horizontal orientation,
#               tall monitor (anything higher than wide) gets vertical orientation
default-root-container-orientation = 'auto'

key-mapping.preset = 'qwerty'

on-focused-monitor-changed = ['move-mouse monitor-lazy-center']
on-focus-changed = "move-mouse window-lazy-center"

# - Per monitor:  gaps.outer.top = [{ monitor.main = 16 }, { monitor."built-in" = 32 }, 24]
[gaps]
inner.horizontal = 5
inner.vertical =   5

outer.bottom =     12    
outer.left =       12
outer.right =      12
outer.top =        12

[key-mapping.key-notation-to-key-code]
Code = 'c'
Media = 'm'
Office = 'o'
Private = 'p'
Research = 'r'
Slack = 's'
Terminal = 't'

[mode.main.binding]

# Focus direction
ctrl-alt-h = 'focus left'
ctrl-alt-j = 'focus down'
ctrl-alt-k = 'focus up'
ctrl-alt-l = 'focus right'
ctrl-alt-left = 'focus left'
ctrl-alt-down = 'focus down'
ctrl-alt-up = 'focus up'
ctrl-alt-right = 'focus right'
# Switch workspace
# ctrl-alt-b = 'workspace Browser'
ctrl-alt-c = 'workspace Code'
ctrl-alt-m = 'workspace Media'
ctrl-alt-o = 'workspace Office'
ctrl-alt-p = 'workspace Private'
ctrl-alt-r = 'workspace Research'
ctrl-alt-s = 'workspace Slack'
ctrl-alt-t = 'workspace Terminal'

# Move window direction
ctrl-alt-shift-h = 'move left'
ctrl-alt-shift-j = 'move down'
ctrl-alt-shift-k = 'move up'
ctrl-alt-shift-l = 'move right'
ctrl-alt-shift-left = 'move left'
ctrl-alt-shift-down = 'move down'
ctrl-alt-shift-up = 'move up'
ctrl-alt-shift-right = 'move right'

# Move node to workspace
# ctrl-alt-shift-b = 'move-node-to-workspace Browser' #['move-node-to-workspace Browser', 'workspace Browser']
ctrl-alt-shift-c = 'move-node-to-workspace Code' #['move-node-to-workspace Code', 'workspace Code']
ctrl-alt-shift-m = 'move-node-to-workspace Media' #['move-node-to-workspace Media','workspace Media']
ctrl-alt-shift-o = 'move-node-to-workspace Office' #['move-node-to-workspace Office','workspace Office']
ctrl-alt-shift-p = 'move-node-to-workspace Private' #['move-node-to-workspace Office','workspace Office']
ctrl-alt-shift-r = 'move-node-to-workspace Research' #['move-node-to-workspace Research','workspace Research']
ctrl-alt-shift-s = 'move-node-to-workspace Slack' #['move-node-to-workspace Slack', 'workspace Slack']
ctrl-alt-shift-t = 'move-node-to-workspace Terminal' #['move-node-to-workspace Terminal','workspace Terminal']

# Resize
alt-h = 'resize width +100' 
alt-j = 'resize height -50'
alt-k = 'resize height +50'
alt-l = 'resize width -100'

ctrl-alt-space = 'focus-back-and-forth'
# ctrl-alt-space = 'exec-and-forget /Users/torgeir.laurvik/.config/aerospace/focus-back-and-forth-workspace.sh'
ctrl-alt-n = 'workspace-back-and-forth'

# ctrl-alt-enter = 'exec-and-forget /Users/torgeir.laurvik/.config/aerospace/focus-ghostty.sh'
ctrl-alt-enter = 'fullscreen'
ctrl-alt-f = 'fullscreen'

ctrl-alt-comma = 'mode service'

[mode.service.binding]
esc = ['reload-config', 'mode main']
r = ['flatten-workspace-tree', 'mode main'] # reset layout
f = ['layout floating tiling', 'mode main']
a = ['layout accordion tiles', 'mode main']
d = ['layout horizontal vertical', 'mode main']
b = ['balance-sizes', 'mode main']

ctrl-alt-h = ['join-with left', 'mode main']
ctrl-alt-j = ['join-with down', 'mode main']
ctrl-alt-k = ['join-with up', 'mode main']
ctrl-alt-l = ['join-with right', 'mode main']
ctrl-alt-left = ['join-with left', 'mode main']
ctrl-alt-down = ['join-with down', 'mode main']
ctrl-alt-up = ['join-with up', 'mode main']
ctrl-alt-right = ['join-with right', 'mode main']
ctrl-alt-m = ['move-workspace-to-monitor --wrap-around next', 'mode main']

# Auto assign app to workspace
[[on-window-detected]]
if.app-id = 'com.electron.dockerdesktop'
run = "move-node-to-workspace Terminal"
check-further-callbacks = true

# [[on-window-detected]]
# if.app-id ='com.microsoft.VSCode' 
# run = "move-node-to-workspace Code"

[[on-window-detected]]
if.app-id ='com.mitchellh.ghostty' 
run = "move-node-to-workspace Code"
check-further-callbacks = true

[[on-window-detected]]
if.app-id ='com.tidal.desktop'
run = "move-node-to-workspace Media"
check-further-callbacks = true

[[on-window-detected]]
if.app-id ='com.spotify.client'
run = "move-node-to-workspace Media"
check-further-callbacks = true

[[on-window-detected]]
if.app-id = 'com.tinyspeck.slackmacgap'
run = "move-node-to-workspace Slack"
check-further-callbacks = true

[[on-window-detected]]
if.app-id = 'com.tinyapp.TablePlus'
run = "layout tiling"
check-further-callbacks = true

[[on-window-detected]]
if.app-id = 'com.tinyapp.TablePlus'
run = "move-node-to-workspace Terminal"
check-further-callbacks = true

[workspace-to-monitor-force-assignment]
Code = 'main'
Media = 'main'
