return {
  require 'plugins.autopairs',
  require 'plugins.debug',
  require 'plugins.indent_line',
  require 'plugins.lint',
  require 'plugins.neo-tree',
  require 'plugins.cmp',
  require 'plugins.conform',
  -- require 'plugins/hardtime',
  require 'plugins.lspconfig',
  require 'plugins.markview',
  require 'plugins.mini',
  require 'plugins.oil',
  --  require 'plugins/precognition',
  require 'plugins.telescope',
  require 'plugins.todo-comments',
  require 'plugins.tokyonight',
  --  require 'plugins/catppuccin',
  require 'plugins.treesitter',
  require 'plugins.which-key',
  require 'plugins.gitsigns',
}
