# 1. CORE SETTINGS
set -g mouse on
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on
set -g default-terminal "tmux-256color"
set -g terminal-overrides ",xterm-256color:RGB"
set -g status-position top

# 2. KEYBINDINGS
bind r source-file -F "#{config_files}" \; display "Reloaded!"
bind c new-window -c "#{pane_current_path}"
bind Space last-window
bind C-b run-shell "tmux setw -g status \$(tmux show -g -w status | grep -q off && echo on || echo off)"
bind g if-shell -F '#{==:#{session_name},popup}' {
    detach-client
} {
    display-popup -d "#{pane_current_path}" -w90% -h90% -E "tmux attach-session -t popup || tmux new-session -s popup lazygit"
}

# 3. PLUGINS
set -g @plugin 'catppuccin/tmux'
set -g @plugin 'jaclu/tmux-menus'
set -g @plugin 'noscript/tmux-mighty-scroll'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-sensible'

# 4. RESURRECT & CONTINUUM CONFIG
set -g @resurrect-strategy-nvim 'session'
set -g @continuum-restore 'on'
set -g @continuum-save-interval '1'

# 5. CATPPUCCIN CONFIG
set -g @catppuccin_flavour 'mocha'
set -g @catppuccin_window_left_separator ""
set -g @catppuccin_window_right_separator " "
set -g @catppuccin_window_middle_separator " █"
set -g @catppuccin_window_number_position "right"
set -g @catppuccin_window_default_fill "number"
set -g @catppuccin_window_current_fill "number"
set -g @catppuccin_window_current_text "#{pane_current_path}"

set -g @catppuccin_status_modules_right "directory session"
set -g @catppuccin_status_left_separator  " "
set -g @catppuccin_status_right_separator ""
set -g @catppuccin_status_fill "icon"
set -g @catppuccin_status_connect_separator "no"
set -g @catppuccin_directory_text "#{pane_current_path}"

# 6. INITIALIZE TPM
# Ensure you have cloned tpm into this specific path first!
run '~/.config/tmux/plugins/tpm/tpm'




set -g @plugin 'tmux-plugins/tpm'

